/**
 * Test for Vite asset path rewriting
 *
 * This test verifies that react-onchain correctly rewrites asset paths
 * generated by Vite, which uses absolute paths like "/assets/file.svg"
 */

import { describe, it, beforeEach, afterEach } from 'node:test';
import assert from 'node:assert';
import { rewriteJs } from '../core/rewriting/jsRewriter.js';
import { rewriteHtml } from '../core/rewriting/htmlRewriter.js';
import { resolveAssetPath, createAssetPathPattern } from '../core/utils.js';
import { writeFile, mkdir, rm } from 'fs/promises';
import { join } from 'path';
import { tmpdir } from 'os';

describe('Vite Asset Path Rewriting', () => {
  let testDir: string;
  let buildDir: string;

  beforeEach(async () => {
    // Create a temporary test directory
    testDir = join(tmpdir(), `react-onchain-vite-test-${Date.now()}`);
    buildDir = join(testDir, 'dist');
    await mkdir(join(buildDir, 'assets'), { recursive: true });
  });

  afterEach(async () => {
    await rm(testDir, { recursive: true, force: true });
  });

  it('should match Vite absolute path patterns', () => {
    const pattern = createAssetPathPattern();

    const testCases = [
      { input: '"/assets/react-CHdo91hT.svg"', shouldMatch: true },
      { input: '"/vite.svg"', shouldMatch: true },
      { input: '"/assets/index-COcDBgFa.css"', shouldMatch: true },
      { input: '"/assets/index-DXS1psJx.js"', shouldMatch: true },
      { input: '"https://external.com/file.js"', shouldMatch: false }, // External URL
      { input: '"data:image/svg+xml;base64,..."', shouldMatch: false }, // Data URI
    ];

    for (const testCase of testCases) {
      const matches = testCase.input.match(pattern);
      if (testCase.shouldMatch) {
        assert.ok(matches, `Expected pattern to match: ${testCase.input}`);
      } else {
        assert.ok(!matches, `Expected pattern NOT to match: ${testCase.input}`);
      }
    }
  });

  it('should resolve Vite absolute paths correctly', () => {
    // Vite uses absolute paths from root
    const resolved1 = resolveAssetPath('/assets/react.svg', 'assets/index.js', buildDir);
    assert.strictEqual(resolved1, 'assets/react.svg');

    const resolved2 = resolveAssetPath('/vite.svg', 'index.html', buildDir);
    assert.strictEqual(resolved2, 'vite.svg');

    // Assets within the assets directory
    const resolved3 = resolveAssetPath('/assets/index.css', 'assets/index.js', buildDir);
    assert.strictEqual(resolved3, 'assets/index.css');
  });

  it('should rewrite Vite JavaScript bundle with asset references', async () => {
    // Create a mock Vite bundle with asset references
    const mockJsContent = `
const A0="/assets/react-CHdo91hT.svg",_0="/vite.svg";
function O0(){
  return jsx("img",{src:_0,className:"logo",alt:"Vite logo"});
}
`;

    const jsPath = join(buildDir, 'assets', 'index.js');
    await writeFile(jsPath, mockJsContent);

    // Create URL map with the asset inscription URLs
    const urlMap = new Map<string, string>();
    urlMap.set('assets/react-CHdo91hT.svg', '/content/abc123_0');
    urlMap.set('vite.svg', '/content/def456_0');

    // Rewrite the JS file
    const rewritten = await rewriteJs(jsPath, buildDir, 'assets/index.js', urlMap);

    // Verify the paths were rewritten
    assert.ok(
      rewritten.includes('/content/abc123_0'),
      'Rewritten content should include react.svg inscription URL'
    );
    assert.ok(
      rewritten.includes('/content/def456_0'),
      'Rewritten content should include vite.svg inscription URL'
    );
    assert.ok(
      !rewritten.includes('/assets/react-CHdo91hT.svg'),
      'Rewritten content should not include original react.svg path'
    );
    assert.ok(
      !rewritten.includes('/vite.svg'),
      'Rewritten content should not include original vite.svg path'
    );
  });

  it('should rewrite Vite HTML with asset references', async () => {
    const mockHtmlContent = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>vite-test</title>
    <script type="module" crossorigin src="/assets/index-DXS1psJx.js"></script>
    <link rel="stylesheet" crossorigin href="/assets/index-COcDBgFa.css">
  </head>
  <body>
    <div id="root"></div>
  </body>
</html>`;

    const htmlPath = join(buildDir, 'index.html');
    await writeFile(htmlPath, mockHtmlContent);

    const urlMap = new Map<string, string>();
    urlMap.set('vite.svg', '/content/vite_icon_inscription');
    urlMap.set('assets/index-DXS1psJx.js', '/content/js_bundle_inscription');
    urlMap.set('assets/index-COcDBgFa.css', '/content/css_bundle_inscription');

    const rewritten = await rewriteHtml(htmlPath, buildDir, 'index.html', urlMap);

    assert.ok(rewritten.includes('/content/vite_icon_inscription'), 'Should rewrite vite.svg path');
    assert.ok(
      rewritten.includes('/content/js_bundle_inscription'),
      'Should rewrite JS bundle path'
    );
    assert.ok(
      rewritten.includes('/content/css_bundle_inscription'),
      'Should rewrite CSS bundle path'
    );
    assert.ok(!rewritten.includes('/vite.svg'), 'Should remove original vite.svg path');
    assert.ok(!rewritten.includes('/assets/index-DXS1psJx.js'), 'Should remove original JS path');
    assert.ok(!rewritten.includes('/assets/index-COcDBgFa.css'), 'Should remove original CSS path');
  });

  it('should handle multiple asset types in Vite bundle', async () => {
    const mockJsContent = `
const logo="/assets/logo.svg";
const image="/assets/photo.jpg";
const font="/assets/font.woff2";
const video="/assets/video.mp4";
`;

    const jsPath = join(buildDir, 'assets', 'bundle.js');
    await writeFile(jsPath, mockJsContent);

    const urlMap = new Map<string, string>();
    urlMap.set('assets/logo.svg', '/content/logo_inscription');
    urlMap.set('assets/photo.jpg', '/content/photo_inscription');
    urlMap.set('assets/font.woff2', '/content/font_inscription');
    urlMap.set('assets/video.mp4', '/content/video_inscription');

    const rewritten = await rewriteJs(jsPath, buildDir, 'assets/bundle.js', urlMap);

    assert.ok(rewritten.includes('/content/logo_inscription'), 'Should rewrite SVG');
    assert.ok(rewritten.includes('/content/photo_inscription'), 'Should rewrite JPG');
    assert.ok(rewritten.includes('/content/font_inscription'), 'Should rewrite font');
    assert.ok(rewritten.includes('/content/video_inscription'), 'Should rewrite video');
    assert.ok(!rewritten.includes('/assets/logo.svg'), 'Should remove original SVG path');
    assert.ok(!rewritten.includes('/assets/photo.jpg'), 'Should remove original JPG path');
    assert.ok(!rewritten.includes('/assets/font.woff2'), 'Should remove original font path');
    assert.ok(!rewritten.includes('/assets/video.mp4'), 'Should remove original video path');
  });

  it('should not rewrite external URLs or data URIs', async () => {
    const mockJsContent = `
const external="https://cdn.example.com/file.js";
const dataUri="data:image/svg+xml;base64,PHN2Zy8+";
const local="/assets/local.svg";
`;

    const jsPath = join(buildDir, 'assets', 'bundle.js');
    await writeFile(jsPath, mockJsContent);

    const urlMap = new Map<string, string>();
    urlMap.set('assets/local.svg', '/content/local_inscription');

    const rewritten = await rewriteJs(jsPath, buildDir, 'assets/bundle.js', urlMap);

    // External URL and data URI should remain unchanged
    assert.ok(
      rewritten.includes('https://cdn.example.com/file.js'),
      'Should preserve external URL'
    );
    assert.ok(rewritten.includes('data:image/svg+xml;base64,PHN2Zy8+'), 'Should preserve data URI');

    // Local asset should be rewritten
    assert.ok(rewritten.includes('/content/local_inscription'), 'Should rewrite local asset');
    assert.ok(!rewritten.includes('/assets/local.svg'), 'Should remove original local path');
  });
});
